name: Test documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Check docs coverage
        run: npm run check-docs
      - name: Build English site
        run: npm run build:en
      - name: Build Japanese site
        run: npm run build:ja
